typography_spectrum: 0.57214
color:
  brandColors:
    - '#ffffff'
    - '#1c232b'
    - '#0097ce'
    - '#ee4c9b'
    - '#e3e42d'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74654
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Stacy Westbrook
  email: stacy@swestbrook.com
  url: 'http://www.swestbrook.com'
name: swestbrook
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: I made this.
    id: ff1dd906-9190-43f1-985e-8d961c0641bf
    type: content
favicon: null
title: Stacy Westbrook
description: Creative strategy & innovationand also bikes
purpose: []
