name: swestbrook
favicon: null
layout_spectrum: 0.74654
typography_spectrum: 0.57214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c232b'
    - '#0097ce'
    - '#ee4c9b'
    - '#e3e42d'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
